# Generated by Django 4.2.13 on 2024-06-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Wishlist",
        ),
    ]
