# Generated by Django 5.0.6 on 2024-05-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_subscription", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribeduser",
            name="email",
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
