# Generated by Django 5.0.6 on 2024-09-18 07:56

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=news.models.news_image_file_path,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("hottest", "The Hottest"),
                            ("choice", "HopHop choice"),
                            ("love", "One Love"),
                            ("secret", "Customer Secret"),
                            ("default", "Default"),
                        ],
                        default="default",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
