# Generated by Django 5.0.6 on 2024-07-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Status Pending"),
                    ("Paid", "Status Paid"),
                    ("Cancelled", "Status Cancelled"),
                    ("Refunded", "Status Refunded"),
                    ("Shipped", "Status Shipped"),
                    ("Delivered", "Status Delivered"),
                    ("Completed", "Status Completed"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
