# Generated by Django 5.0.6 on 2024-09-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_alter_order_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-id"]},
        ),
    ]
