# Generated by Django 5.0.6 on 2024-09-14 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0003_alter_order_options"),
        ("checkout", "0005_remove_order_paid_remove_order_status_and_more"),
    ]

    operations = []
