# Generated by Django 5.0.6 on 2024-09-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0006_merge_20240914_1135"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(default="no-email@example.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_type",
            field=models.CharField(default="card", max_length=20),
            preserve_default=False,
        ),
    ]
