# Generated by Django 5.0.6 on 2024-09-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0007_alter_order_email_alter_order_payment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                choices=[("card", "Card"), ("crypto", "Cryptocurrency")], max_length=20
            ),
        ),
    ]
