# Generated by Django 5.0.6 on 2024-09-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0008_alter_order_payment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("canceled", "Canceled"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
