# Generated by Django 5.0.6 on 2024-09-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0009_alter_order_order_status_alter_order_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                choices=[("card", "Card"), ("crypto", "Cryptocurrency")],
                default="card",
                max_length=20,
            ),
        ),
    ]
