# Generated by Django 5.0.6 on 2024-09-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0011_alter_orderitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                choices=[("card", "Card"), ("crypto", "Cryptocurrency")], max_length=20
            ),
        ),
    ]
