# Generated by Django 5.0.6 on 2024-10-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0012_alter_order_payment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Status Pending"),
                    ("In Progress", "Status In Progress"),
                    ("In Transit", "Status In Transit"),
                    ("Delivered", "Status Delivered"),
                    ("Canceled", "Status Canceled"),
                    ("Returned", "Status Returned"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
