# Generated by Django 5.0.6 on 2024-07-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=17, verbose_name="phone number"
            ),
        ),
    ]
