# Generated by Django 5.0.6 on 2024-09-09 12:55

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_passwordreset"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="avatar",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=authentication.models.customer_image_file_path,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="shipping_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="shipping_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="shipping_country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="shipping_postcode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
