# Generated by Django 5.0.6 on 2024-09-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_customer_avatar_customer_shipping_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=17, unique=True, verbose_name="phone number"
            ),
        ),
    ]
