# Generated by Django 5.0.6 on 2024-09-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_customer_avatar_customer_shipping_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["id"],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
