# Generated by Django 5.0.6 on 2024-09-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_customer_options"),
        ("authentication", "0005_alter_customer_phone_number"),
    ]

    operations = []
