# Generated by Django 5.0.6 on 2024-10-02 16:10

import utils.data_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_alter_customer_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(
                max_length=17,
                null=True,
                unique=True,
                validators=[utils.data_validation.validate_phone_number],
                verbose_name="phone number",
            ),
        ),
    ]
