# Generated by Django 5.0.6 on 2024-05-21 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_product_options_alter_productimage_options_and_more"),
        ("shop", "0003_auto_20240519_2046"),
    ]

    operations = []
