# Generated by Django 5.0.6 on 2024-06-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_product_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="uploads/category/"
            ),
        ),
    ]
