# Generated by Django 5.0.6 on 2024-06-09 13:28

from django.db import migrations


def load_fixture_data(apps, schema_editor):
    from django.core.management import call_command

    # call_command("loaddata", "initial_data.json", app_label="shop")


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_category_image"),
    ]

    # operations = [
    #     migrations.RunPython(load_fixture_data),
    # ]
