# Generated by Django 4.2.13 on 2024-06-15 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_product_price_alter_productimage_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productattributes",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_attributes",
                to="shop.product",
            ),
        ),
    ]
