# Generated by Django 5.0.6 on 2024-07-23 11:25

from django.db import migrations, models


def load_fixture_data(apps, schema_editor):
    from django.core.management import call_command

    call_command("loaddata", "initial_data.json", app_label="shop")


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_alter_productattributes_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(load_fixture_data),
    ]
