# Generated by Django 5.0.6 on 2024-09-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="SKU",
            field=models.CharField(max_length=100),
        ),
    ]
