# Generated by Django 5.0.6 on 2024-09-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_alter_product_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
