# Generated by Django 5.0.6 on 2024-10-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_alter_product_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ["id"]},
        ),
    ]
