# Generated by Django 4.2.13 on 2024-06-27 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="old_cart",
        ),
    ]
