# Generated by Django 4.2.13 on 2024-06-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="customer",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
